#!/bin/bash
# Setup Finnhub API for Stock Market Monitor

echo "=========================================="
echo "Stock Market Monitor - Finnhub Setup"
echo "=========================================="
echo ""
echo "To use real stock prices via Finnhub API:"
echo ""
echo "1. Visit: https://finnhub.io/"
echo "2. Click 'Sign Up' for a free account"
echo "3. Copy your API key from the dashboard"
echo "4. Create a .env file with:"
echo ""
echo "   FINNHUB_API_KEY=your_api_key_here"
echo ""
echo "5. Save and run the monitor:"
echo ""
echo "   python web_app.py"
echo "   # or"
echo "   python main.py --demo"
echo ""
echo "That's it! The monitor will fetch real prices from Finnhub."
echo "Free tier: 60 API calls/minute (plenty for monitoring)"
echo ""
echo "=========================================="
